name: Border0 MongoDB Query
on:
  workflow_dispatch:

jobs:
  query-mongodb-via-border0:
    runs-on: ubuntu-latest
    env:
      # You can override this in repo secrets if you like
      MONGO_URI: ${{ secrets.MONGO_URI || 'mongodb://ddb-password:27017/library' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Border0 CLI
        run: |
          sudo curl -L https://download.border0.com/linux_amd64/border0 -o /usr/local/bin/border0
          sudo chmod +x /usr/local/bin/border0

      - name: Start Border0 client
        env:
          BORDER0_TOKEN: ${{ secrets.BORDER0_TOKEN }}
        run: |
          echo "$BORDER0_TOKEN" > /tmp/border0.token
          sudo border0 node install --start-vpn --token from:file:/tmp/border0.token
          # give the client a moment to come up and route traffic
          sleep 5

      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg curl ca-certificates
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh --version

      - name: Wait for MongoDB to be reachable
        run: |
          for i in {1..12}; do
            if mongosh "$MONGO_URI" --eval "db.runCommand({ ping: 1 })" --quiet >/dev/null 2>&1; then
              echo "MongoDB reachable"
              exit 0
            fi
            echo "Waiting for MongoDB... attempt $i"
            sleep 5
          done
          echo "MongoDB not reachable after retries"
          exit 1

      - name: Run sample query
        id: mongoquery
        run: |
          echo 'db.books.find().limit(10).toArray()' | mongosh "$MONGO_URI" --quiet | tee /tmp/query_output.json

      - name: Upload query output
        uses: actions/upload-artifact@v4
        with:
