name: Border0 exit-node demo

on:
  workflow_dispatch:

jobs:
  test-border0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print public IP before
        run: curl -s https://ipinfo.io | jq '{ip, city, region,country, org}'

      - name: Install Border0 CLI
        run: |
          sudo curl -L https://download.border0.com/linux_amd64/border0 \
            -o /usr/local/bin/border0
          sudo chmod +x /usr/local/bin/border0

      - name: Start Border0 VPN and set Exit Node
        env:
          BORDER0_TOKEN: ${{ secrets.BORDER0_TOKEN }}
          BORDER0_EXIT_NODE: ${{ secrets.BORDER0_EXIT_NODE }}
        run: |
          echo "$BORDER0_TOKEN" > /tmp/border0.token
          sudo border0 node install --start-vpn --token from:file:/tmp/border0.token
          sleep 10  # Give it a few seconds to initialize
          border0 node exitnode set "$BORDER0_EXIT_NODE"

      - name: Print public IP after
        run: curl -s https://ipinfo.io | jq '{ip, city, region,country, org}'
